name: "JFrog Integration Example"
on: push

jobs:
  build:
     runs-on: windows-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v2
         env:  
           JF_URL: ${{ secrets.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
       - name: Setup Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
           
       - name: Set CLI Config for Resolution
         run: jf pip-config --global=true --repo-resolve=demo-python
           
       - name: Install Deps
         run: jf pip install .
           
       - name: Run tests
         run: python -m unittest discover
         
       - name: Publish to Artifactory
         run: jf rt u "./dist/*.tar.gz" demo-python --build-name=$GITHUB_RUN_ID --build-number=$GITHUB_RUN_NUMBER
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish
