name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install
    - run: npm test
    - run: npm pack
    - run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      id: package
    - name: Check if artifact exists in Artifactory
      run: |
        artifactExists=$(jf rt s "demo-npm/frog-utils-${{ steps.package.outputs.version }}.tgz" && echo 'true' || echo 'false')
        echo "exists=$artifactExists" >> $GITHUB_ENV
      shell: bash
    - name: Publish to Artifactory if not already present
      run: |
        if ("$env:exists" -eq "false") {
          jf rt u "./frog-utils-${{ steps.package.outputs.version }}.tgz" demo-npm --build-name=$GITHUB_RUN_ID --build-number=$GITHUB_RUN_NUMBER
          Write-Output "Artifact successfully uploaded to Artifactory."
        } else {
          Write-Output "This version of artifact already present, no need to upload."
        }
      shell: pwsh
