name: "JFrog Integration Example"
on: push

jobs:
  build:
     runs-on: windows-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v2
         env:  
           JF_URL: ${{ secrets.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

       - name: Setup Node
         uses: actions/setup-node@v2
         with:
           node-version: '14'
           
       - name: Install Dependencies
         run: npm install
         
       - name: Run tests
         run: npm test

       - name: Pack
         run: npm pack
         
       - name: Get version
         id: packagejson
         run: |
           echo "::set-output name=version::$(node -p "require('./package.json').version")"
         
       - name: Upload to Artifactory
         run: |
           jf rt u "./frog-utils-${{ steps.packagejson.outputs.version }}.tgz" demo-npm --build-name=$GITHUB_RUN_ID --build-number=$GITHUB_RUN_NUMBER
