name: "JFrog Integration Example"
on: push

jobs:
  build:
    runs-on: windows-latest
       
    steps:
      - name: Checkout
        uses: actions/checkout@v2
         
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:  
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
      - name: Setup Node npm
        uses: actions/setup-node@v2
           
      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test
         
      - name: Pack
        run: npm pack
      
      - name: Get version
        id: packagejson
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
        
      - name: Check if artifact exists in Artifactory
        id: check_artifact
        shell: pwsh
        run: |
          $artifactExists = jf rt s "demo-npm/frog-utils-${{ steps.packagejson.outputs.version }}.tgz" || true
          if ($artifactExists -like "*Found 0 artifacts*") {
            echo "Artifact does not exist in Artifactory."
            echo "::set-output name=exists::false"
          } else {
            echo "Artifact exists in Artifactory."
            echo "::set-output name=exists::true"
          }
          
      - name: Publish
        shell: pwsh
        run: |
          if ("${{ steps.check_artifact.outputs.exists }}" -eq "false") {
            jf rt u "./frog-utils-${{ steps.packagejson.outputs.version }}.tgz" demo-npm --build-name=$GITHUB_RUN_ID --build-number=$GITHUB_RUN_NUMBER
            Write-Output "Artifact successfully uploaded to Artifactory."
          } else {
            Write-Output "This version of artifact already present, no need to upload."
          }
