name: Upload to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Pack for npm
      run: npm pack
      - run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
        id: package

    - name: Check artifact
      id: check_artifact
      run: |
        artifactExists=$(jfrog rt s "demo-npm/frog-utils-${{ steps.package.outputs.version }}.tgz" || echo false)
        echo "ARTIFACT_EXISTS=$artifactExists" >> $GITHUB_ENV
        echo "Artifact exists: $artifactExists"

    - name: Upload to Artifactory if not exists
      run: |
        if [ "${{ env.ARTIFACT_EXISTS }}" = "false" ]; then
          jfrog rt u "./frog-utils-${{ steps.package.outputs.version }}.tgz" demo-npm --build-name=$GITHUB_RUN_ID --build-number=$GITHUB_RUN_NUMBER
          echo "Artifact successfully uploaded to Artifactory."
        else
          echo "This version of artifact already present, no need to upload."
        fi
